### ISSUE TITLE
Questions re: grid and figcaption

### ISSUE THREAD

**Issue by C-G-G** [C-G-G/grid-layout#1]
I'm trying to figure out the top part (The Seven Wonders...) @960em, whether I should use float, flex, or turn it to a grid like the bottom part? Or should the whole layout be a big grid? (maybe I'm unnecessarily confusing myself between flex and grid)

Also, Markbot is expecting figcaption but also h2. I played around a bit but figcaption worked neither at top (Seven Wonders) nor bottom. Any tips?

Thanks @thomasjbradley

**Comment by thomasjbradley** [comment]
I’m using a grid in the top Seven Wonders part.

I have an `<h2>` inside my `<figcaption>` for the most-est semantics ;)
